### ISSUE TITLE
Question about settings

### ISSUE THREAD

**Issue by stratxgy** [Exunys/Aimbot-V3#10]
Using orion lib, https://github.com/shlexware/Orion/blob/main/Documentation.md
how should I go about changing the settings, especially with color pickers and such?

I was thinking using a flag or something of the sort. 

Yes, I did read the dropdown on the readme with all the settings, and I tried copying and pasting that with settings into a button and it didn't work.

Thanks so much, Exunys.

**Comment by Exunys** [comment]
Take a reference from my script, [AirHub V2](https://github.com/Exunys/AirHub-V2).

Everything is documented on the README.md page, you basically just change them from the environment `ExunysDeveloperAimbot`.

Example

```lua
loadstring(game:HttpGet("https://raw.githubusercontent.com/Exunys/Aimbot-V3/main/src/Aimbot.lua"))()

-- Assuming you have a section named "Section"

Section:CreateToggle({
   Name = "Enabled",
   Flag = "Aimbot_Enabled",
   Default = ExunysDeveloperAimbot.Settings.Enabled,
   Callback = function(Value)
     ExunysDeveloperAimbot.Settings.Enabled = Value
   end
})
```
