### ISSUE TITLE
MENU

### ISSUE THREAD

**Issue by HEYDARPRO** [Exunys/Aimbot-V3#11]
So pretty much when i copy "The module's configurable settings" into my executor and without changing anything I press inject it doesn't work and when i change the options in the script it also doesn't work like it doesn't open pls help. because I wanna change wallcheck and teamcheck to true. Also is there a interactive ingame menu for it??

**Comment by Exunys** [comment]
Can you be more specific? Attach error messages if possible.

Here's an example if you are looking for this:
```lua
loadstring(game:HttpGet("https://raw.githubusercontent.com/Exunys/Aimbot-V3/main/src/Aimbot.lua"))()
ExunysDeveloperAimbot.Settings.TeamCheck = false
ExunysDeveloperAimbot.Settings.WallCheck = true
```

**Comment by HEYDARPRO** [comment]
wait i never put the loadstring with the menu do i have to??

**Comment by HEYDARPRO** [comment]
there is no erorr message it just doesn't work

**Comment by Exunys** [comment]
Yes, of course. Read the README.md document I updated the section about configuring the settings.

**Comment by HEYDARPRO** [comment]
if this is the correct way to put the code then for some reason it doesn't work: local Aimbot = loadstring(game:HttpGet("https://raw.githubusercontent.com/Exunys/Aimbot-V3/main/src/Aimbot.lua"))()
getgenv().ExunysDeveloperAimbot = {
	DeveloperSettings = {
		UpdateMode = "RenderStepped",
		TeamCheckOption = "TeamColor",
		RainbowSpeed = 1 -- Bigger = Slower
	},

	Settings = {
		Enabled = true,

		TeamCheck = true,
		AliveCheck = true,
		WallCheck = true,

		OffsetToMoveDirection = false, -- Prediction
		OffsetIncrement = 15, -- Min: 1; Max: 30 -- Amplitude

		Sensitivity = 0, -- Animation length (in seconds) before fully locking onto target / CFrame Sensitivity
		Sensitivity2 = 3.5, -- mousemoverel Sensitivity

		LockMode = 1, -- 1 = CFrame; 2 = mousemoverel
		LockPart = "Head", -- Body part to lock on

		TriggerKey = Enum.UserInputType.MouseButton2,
		Toggle = false
	},

	FOVSettings = {
		Enabled = true,
		Visible = true,

		Radius = 200, -- Field Of View
		NumSides = 60,

		Thickness = 1,
		Transparency = 1,
		Filled = false,

		RainbowColor = false,
		RainbowOutlineColor = false,
		Color = Color3.fromRGB(255, 255, 255),
		OutlineColor = Color3.fromRGB(0, 0, 0),
		LockedColor = Color3.fromRGB(255, 150, 150)
	}
}

**Comment by HEYDARPRO** [comment]
also the code u sent doesnt work ether

**Comment by stratxgy** [comment]
> Yes, of course. Read the README.md document I updated the section about configuring the settings.

What are all the lockparts that you can configure? (exunysdeveloperaimbot.settings.lockpart = ec: head, torso, neck 

basically what are all the things i can put here?

**Comment by Exunys** [comment]
@HEYDARPRO I just told you, that is NOT the way you configure it. Read the README.md document please because I keep repeating myself for no reason.

@Stratxgy Basically the character rigtype parts. For R6 you have "Left Arm", "Right Leg", "Torso" etc. and for R15 you have "LowerTorso", "UpperTorso", "LeftLowerLeg", "RightUpperLeg", "LeftHand", "RightFoot" etc.

Here's a full list including R6 and R15 limbs:

```lua
local Parts = {"Head", "HumanoidRootPart", "Torso", "Left Arm", "Right Arm", "Left Leg", "Right Leg", "LeftHand", "RightHand", "LeftLowerArm", "RightLowerArm", "LeftUpperArm", "RightUpperArm", "LeftFoot", "LeftLowerLeg", "UpperTorso", "LeftUpperLeg", "RightFoot", "RightLowerLeg", "LowerTorso", "RightUpperLeg"}
```

**Comment by stratxgy** [comment]
> @HEYDARPRO I just told you, that is NOT the way you configure it. Read the README.md document please because I keep repeating myself for no reason.
> 
> @Stratxgy Basically the character rigtype parts. For R6 you have "Left Arm", "Right Leg", "Torso" etc. and for R15 you have "LowerTorso", "UpperTorso", "LeftLowerLeg", "RightUpperLeg", "LeftHand", "RightFoot" etc.
> 
> Here's a full list including R6 and R15 limbs:
> 
> ```lua
> local Parts = {"Head", "HumanoidRootPart", "Torso", "Left Arm", "Right Arm", "Left Leg", "Right Leg", "LeftHand", "RightHand", "LeftLowerArm", "RightLowerArm", "LeftUpperArm", "RightUpperArm", "LeftFoot", "LeftLowerLeg", "UpperTorso", "LeftUpperLeg", "RightFoot", "RightLowerLeg", "LowerTorso", "RightUpperLeg"}
> ```

thanks for being helpful ❤️
