### ISSUE TITLE
Error appears when loadstring is executed

### ISSUE THREAD

**Issue by Zaxiss44** [Exunys/Aimbot-V3#13]
I can't even add this library into script because when I add the loadstring, this error appears

![image](https://github.com/user-attachments/assets/76305c95-7b83-497a-9660-842dd3ff77e7)

**Comment by ZaxissNoMalware** [comment]
That's how I added into script:

![image](https://github.com/user-attachments/assets/2db205f7-6e90-4aea-aad8-80ee7222b943)

**Comment by Exunys** [comment]
Your executor doesn't support it. Use Solara or Wave.
