### ISSUE TITLE
How do I actually install this thing into Zepplin Wars!?!? You devs never NEVER detail HOW to install these aimbots into ROBLOX!! What console do I need to open? What file do I need to get to in ROBLOX's main files??

### ISSUE THREAD

**Issue by LunarAnticGitHub** [Exunys/Aimbot-V3#5]

**Comment by Exunys** [comment]
This is a module made by a developer for developers and it is not 100% intended for users like yourself. If you do want to use the aimbot refer to AirHub V2 (you can find it on my profile, it also utilizes an ESP module) and to use it you need a script execution engine which you can find one here: whatexpsare.online

Once you find an executor, you need to inject it and paste the script inside the IDE of the application and press execute. If the script doesn't appear then that means that the executor doesn't support it or you got lost somewhere along the installation steps. If I haven't been very clear you can look on YouTube or V3rmillion on how to download and install a working ROBLOX script executor.
